/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MlLabRouteImport } from './routes/ml-lab'
import { Route as AuditIndexRouteImport } from './routes/audit.index'
import { Route as AuditIdRouteImport } from './routes/audit.$id'
import { Route as CompareIdRouteImport } from './routes/compare.$id'
import { Route as RemediateIdRouteImport } from './routes/remediate.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MlLabRoute = MlLabRouteImport.update({
  id: '/ml-lab',
  path: '/ml-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIdRoute = AuditIdRouteImport.update({
  id: '/audit/$id',
  path: '/audit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIdRoute = CompareIdRouteImport.update({
  id: '/compare/$id',
  path: '/compare/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RemediateIdRoute = RemediateIdRouteImport.update({
  id: '/remediate/$id',
  path: '/remediate/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRoute
  '/history': typeof HistoryRoute
  '/ml-lab': typeof MlLabRoute
  '/audit/$id': typeof AuditIdRoute
  '/compare/$id': typeof CompareIdRoute
  '/remediate/$id': typeof RemediateIdRoute
  '/audit/': typeof AuditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRoute
  '/history': typeof HistoryRoute
  '/ml-lab': typeof MlLabRoute
  '/audit/$id': typeof AuditIdRoute
  '/compare/$id': typeof CompareIdRoute
  '/remediate/$id': typeof RemediateIdRoute
  '/audit': typeof AuditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRoute
  '/history': typeof HistoryRoute
  '/ml-lab': typeof MlLabRoute
  '/audit/$id': typeof AuditIdRoute
  '/compare/$id': typeof CompareIdRoute
  '/remediate/$id': typeof RemediateIdRoute
  '/audit/': typeof AuditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/datasets'
    | '/history'
    | '/ml-lab'
    | '/audit/$id'
    | '/compare/$id'
    | '/remediate/$id'
    | '/audit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/datasets'
    | '/history'
    | '/ml-lab'
    | '/audit/$id'
    | '/compare/$id'
    | '/remediate/$id'
    | '/audit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/datasets'
    | '/history'
    | '/ml-lab'
    | '/audit/$id'
    | '/compare/$id'
    | '/remediate/$id'
    | '/audit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DatasetsRoute: typeof DatasetsRoute
  HistoryRoute: typeof HistoryRoute
  MlLabRoute: typeof MlLabRoute
  AuditIdRoute: typeof AuditIdRoute
  CompareIdRoute: typeof CompareIdRoute
  RemediateIdRoute: typeof RemediateIdRoute
  AuditIndexRoute: typeof AuditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-lab': {
      id: '/ml-lab'
      path: '/ml-lab'
      fullPath: '/ml-lab'
      preLoaderRoute: typeof MlLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/$id': {
      id: '/audit/$id'
      path: '/audit/$id'
      fullPath: '/audit/$id'
      preLoaderRoute: typeof AuditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$id': {
      id: '/compare/$id'
      path: '/compare/$id'
      fullPath: '/compare/$id'
      preLoaderRoute: typeof CompareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remediate/$id': {
      id: '/remediate/$id'
      path: '/remediate/$id'
      fullPath: '/remediate/$id'
      preLoaderRoute: typeof RemediateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DatasetsRoute: DatasetsRoute,
  HistoryRoute: HistoryRoute,
  MlLabRoute: MlLabRoute,
  AuditIdRoute: AuditIdRoute,
  CompareIdRoute: CompareIdRoute,
  RemediateIdRoute: RemediateIdRoute,
  AuditIndexRoute: AuditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
